version: '3.8'
services:
  api_node:
    build:
      context: .
    image: api_node_js
    container_name: api_node_nc
    ports:
      - "3333:3333"
      - "5555:5555"
    working_dir: /app
    depends_on:
      sql_database:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://api_node_user:password99@sql_database:3306/api_node_sql
    networks:
      - node_network
    restart: unless-stopped

  sql_database:
    image: mysql:8.0
    container_name: sql_database_nc
    environment:
      - MYSQL_ROOT_PASSWORD=passwordroot99
      - MYSQL_DATABASE=api_node_sql
      - MYSQL_USER=api_node_user
      - MYSQL_PASSWORD=password99
    volumes:
      - db_data:/var/lib/mysql
      # - ./initdb.d:/etc/mysql/initdb.d
    networks:
      - node_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

volumes:
  db_data:


networks:
  node_network:
    driver: bridge
